const commandList = [
	{ name: 'menu', aliases: ['help', 'start'], description: 'Tampilkan menu bot' },
	{ name: 'ping', aliases: ['p'], description: 'Cek respon bot' },
	{ name: 'eval', aliases: ['ev'], description: 'Evaluasi kode JavaScript owner' },
	{ name: 'backup', aliases: ['dbbackup'], description: 'Backup database owner' },
	{ name: 'restore', aliases: ['dbrestore'], description: 'Restore database dari backup JSON owner' },
	{ name: 'logs', aliases: ['logtail'], description: 'Tail log runtime owner' },
	{ name: 'remind', aliases: ['reminder', 'schedule', 'scheduler'], description: 'Set reminder owner' },
	{ name: 'sticker', aliases: ['s'], description: 'Ubah image/video jadi sticker' },
	{ name: 'toaudio', aliases: ['tomp3'], description: 'Ubah video/audio jadi MP3' },
	{ name: 'toptt', aliases: ['vn'], description: 'Ubah video/audio jadi voice note' },
	{ name: 'tovid', aliases: ['togif'], description: 'Ubah sticker jadi video/GIF' },
	{ name: 'update', aliases: ['upgrade'], description: 'Update file bot dan install dependency' },
	{ name: 'tourl', aliases: ['urlfile'], description: 'Upload media ke Catbox' },
	{ name: 'short', aliases: ['shortlink'], description: 'Buat shortlink TinyURL' },
	{ name: 'qr', aliases: ['qrcode'], description: 'Generate QR code dari text/URL' },
	{ name: 'readqr', aliases: ['qrread', 'scanqr'], description: 'Baca QR dari gambar atau URL gambar' },
	{ name: 'tiktok', aliases: ['tt'], description: 'TikTok native: URL → no-watermark, query → search, @user → profil' },
	{ name: 'ttuser', aliases: ['ttprofile', 'tikuser'], description: 'Cek profil TikTok by @username' },
	{ name: 'instagram', aliases: ['ig'], description: 'Downloader Instagram atau tombol halaman asli' },
	{ name: 'youtube', aliases: ['yt', 'ytmp4'], description: 'Downloader YouTube atau tombol halaman asli' },
	{ name: 'lyrics', aliases: ['lirik', 'ly'], description: 'Cari lyric lagu (Genius + lyrics.ovh)' },
	{ name: 'translate', aliases: ['tr', 'tl'], description: 'Translate teks (default ke Bahasa Indonesia)' },
	{ name: 'detect', aliases: ['detlang', 'dlang'], description: 'Deteksi bahasa dari teks' },
	{ name: 'image', aliases: ['imagine', 'ai', 'gen'], description: 'Generate gambar AI dari prompt (Pollinations)' },
	{ name: 'editimage', aliases: ['editimg', 'imgedit'], description: 'Edit gambar AI dari URL/reply gambar + prompt (Pollinations)' },
	{ name: 'imagemodels', aliases: ['models', 'aimodels'], description: 'List model AI image yang tersedia' },
	{ name: 'wiki', aliases: ['wikipedia'], description: 'Cari artikel Wikipedia (id)' },
	{ name: 'surah', aliases: ['quran'], description: 'Tampilkan surah Al-Quran by nomor' },
	{ name: 'ayat', aliases: [], description: 'Tampilkan satu ayat (.ayat 2 255)' },
	{ name: 'surahlist', aliases: ['daftarsurah'], description: 'Daftar 114 surah Al-Quran' },
	{ name: 'sholat', aliases: ['jadwalsholat'], description: 'Jadwal sholat hari ini per kota' },
	{ name: 'cuaca', aliases: ['weather'], description: 'Cuaca global via wttr.in' },
	{ name: 'bmkg', aliases: [], description: 'Cuaca resmi BMKG (Indonesia)' },
	{ name: 'quote', aliases: ['kata'], description: 'Quote random' },
	{ name: 'animequote', aliases: ['anime-quote'], description: 'Quote anime random' },
	{ name: 'fact', aliases: ['fakta'], description: 'Random useless fact' },
	{ name: 'joke', aliases: ['lelucon'], description: 'Random joke (jokeapi)' },
	{ name: 'meme', aliases: [], description: 'Random meme dari Reddit' },
	{ name: 'kateglo', aliases: ['kbbi'], description: 'Kamus Indonesia (definisi + sinonim)' },
	{ name: 'pypi', aliases: ['pip'], description: 'Info package PyPI' },
	{ name: 'ghtrend', aliases: ['github-trending', 'gh-trend'], description: 'GitHub trending repos' },
	{ name: 'ytsearch', aliases: ['youtube-search'], description: 'Cari video YouTube' },
	{ name: 'wp', aliases: ['wallpaper', 'wallhaven'], description: 'Cari wallpaper di Wallhaven' },
	{ name: 'kurs', aliases: ['currency'], description: 'Konversi mata uang (.kurs USD IDR 50)' },
	{ name: 'rates', aliases: ['rate'], description: 'Daftar kurs populer dari base currency' },
	{ name: 'ip', aliases: ['iplookup'], description: 'Lookup info IP / lokasi' },
	{ name: 'reddit', aliases: ['r'], description: 'Lihat post subreddit (.reddit memes top)' },
	{ name: 'berita', aliases: ['news'], description: 'Headline berita Indonesia (CNN/Antara/dll)' },
	{ name: 'ss', aliases: ['screenshot'], description: 'Screenshot halaman web' },
	{ name: 'mediafire', aliases: ['mf'], description: 'Direct link Mediafire dari URL' },
	{ name: 'pin', aliases: ['pinterest', 'pins'], description: 'Scrape media Pinterest' },
	{ name: 'pinnext', aliases: ['nextpin'], description: 'Foto Pinterest berikutnya' },
	{ name: 'anime', aliases: ['ani'], description: 'Cari anime di Samehadaku' },
	{ name: 'stream', aliases: ['samehadaku', 'nonton'], description: 'Ambil stream episode Samehadaku' },
	{ name: 'streamselect', aliases: ['pilihstream'], description: 'Pilih episode stream Samehadaku' },
	{ name: 'streamnext', aliases: ['nextstream'], description: 'Server stream Samehadaku berikutnya' },
	{ name: 'otakudesu', aliases: ['otaku'], description: 'Cari anime di Otakudesu' },
	{ name: 'otakudesulatest', aliases: ['otakulatest', 'otakulatest'], description: 'Episode terbaru Otakudesu' },
	{ name: 'otakudesustream', aliases: ['otakustream'], description: 'Ambil stream episode Otakudesu' },
	{ name: 'otakudesunext', aliases: ['otakunext'], description: 'Hasil/server Otakudesu berikutnya' },
	{ name: 'otakudesuselect', aliases: ['otakuselect'], description: 'Pilih episode stream Otakudesu' },
	{ name: 'anoboy', aliases: ['ano'], description: 'Cari anime di Anoboy' },
	{ name: 'anoboylatest', aliases: ['anolatest', 'anolatest'], description: 'Episode terbaru Anoboy' },
	{ name: 'anoboystream', aliases: ['anostream'], description: 'Ambil stream episode Anoboy' },
	{ name: 'anoboynext', aliases: ['anonext'], description: 'Hasil/server Anoboy berikutnya' },
	{ name: 'anoboyselect', aliases: ['anoselect'], description: 'Pilih episode stream Anoboy' },
	{ name: 'spotify', aliases: ['sp'], description: 'Cari lagu di Spotify' },
	{ name: 'spotifydl', aliases: ['spdl'], description: 'Download lagu dari Spotify URL' },
	{ name: 'spotifynext', aliases: ['spnext'], description: 'Hasil Spotify berikutnya' },
	{ name: 'topanime', aliases: ['topani'], description: 'Top anime Samehadaku' },
	{ name: 'seasonanime', aliases: ['season'], description: 'Anime season sekarang' },
	{ name: 'idch', aliases: ['cekidch', 'cekid'], description: 'Cek ID channel WhatsApp' },
	{ name: 'role', aliases: ['profile', 'me'], description: 'Cek role user' },
	{ name: 'setnama', aliases: ['setname', 'nama'], description: 'Set nama profile bot' },
	{ name: 'welcome', aliases: ['setwelcome'], description: 'Aktif/nonaktif welcome grup' },
	{ name: 'leave', aliases: ['setleave'], description: 'Aktif/nonaktif leave grup' },
	{ name: 'antilink', aliases: ['anti-link'], description: 'Aktif/nonaktif anti-link grup' },
	{ name: 'antispam', aliases: ['anti-spam'], description: 'Aktif/nonaktif anti-spam grup' },
	{ name: 'antidelete', aliases: ['anti-delete'], description: 'Aktif/nonaktif anti-delete grup' },
	{ name: 'groupsetting', aliases: ['groupsettings'], description: 'Cek setting grup' },
	{ name: 'warn', aliases: [], description: 'Beri warn member grup' },
	{ name: 'unwarn', aliases: [], description: 'Kurangi warn member grup' },
	{ name: 'kick', aliases: ['remove'], description: 'Keluarkan member grup' },
	{ name: 'promote', aliases: [], description: 'Jadikan admin grup' },
	{ name: 'demote', aliases: [], description: 'Turunkan admin grup' },
	{ name: 'register', aliases: ['daftar'], description: 'Daftar sebagai member' },
	{ name: 'unregister', aliases: ['unreg'], description: 'Hapus status member' },
	{ name: 'button', aliases: ['buttons'], description: 'Demo quick reply button' },
	{ name: 'list', aliases: ['pilih'], description: 'Demo button pilihan/list' },
	{ name: 'link', aliases: ['url'], description: 'Demo tombol buka link' },
	{ name: 'copy', aliases: ['code'], description: 'Demo tombol salin text' },
	{ name: 'call', aliases: ['phone'], description: 'Demo tombol telepon' },
	{ name: 'owner', aliases: ['creator'], description: 'Tampilkan owner bot' },
	{ name: 'id', aliases: ['jid'], description: 'Cek JID chat' },
	{ name: 'tebakgambar', aliases: ['tg'], description: 'Tebak jawaban dari emoji' },
	{ name: 'tebakkata', aliases: ['tk'], description: 'Tebak kata dari clue' },
	{ name: 'tebakanime', aliases: ['ta'], description: 'Tebak judul anime' },
	{ name: 'slot', aliases: ['slots'], description: 'Slot machine — putar dan dapat XP' },
	{ name: 'coinflip', aliases: ['cf'], description: 'Lempar koin — pilih heads/tails' },
	{ name: 'dice', aliases: ['dadu'], description: 'Lempar dadu' },
	{ name: 'suit', aliases: ['rps'], description: 'Batu gunting kertas vs bot' },
	{ name: 'truth', aliases: [], description: 'Random truth question' },
	{ name: 'dare', aliases: [], description: 'Random dare challenge' },
	{ name: 'ai', aliases: ['chat'], description: 'Chat AI (Pollinations)' },
	{ name: 'aiclear', aliases: [], description: 'Reset context AI chat' },
	{ name: 'google', aliases: ['g'], description: 'Cari di Google via Jina' },
	{ name: 'movie', aliases: ['film'], description: 'Info film dari OMDb' },
	{ name: 'zodiak', aliases: ['horo'], description: 'Ramalan zodiak harian' },
	{ name: 'font', aliases: ['style'], description: 'Ubah teks jadi font stylish' },
	{ name: 'calc', aliases: ['math'], description: 'Kalkulator expression' },
	{ name: 'afk', aliases: [], description: 'Set AFK mode' },
	{ name: 'tagall', aliases: ['everyone'], description: 'Tag semua member grup (admin)' },
	{ name: 'autosticker', aliases: [], description: 'Auto-convert gambar jadi sticker (grup)' },
	{ name: 'antiviewonce', aliases: ['avo'], description: 'Capture view-once message (grup)' },
	{ name: '8ball', aliases: ['magic8'], description: 'Magic 8-ball prediction' },
	{ name: 'tictactoe', aliases: ['ttt'], description: 'Tic tac toe vs bot' },
	{ name: 'hangman', aliases: ['hm'], description: 'Tebak kata hangman' },
	{ name: 'trivia', aliases: ['quiz'], description: 'Trivia question random' },
	{ name: 'api', aliases: [], description: 'Generic API command (80+ endpoints)' },
	{ name: 'encode', aliases: ['enc'], description: 'Encode teks (base64, morse, hex, dll)' },
	{ name: 'decode', aliases: ['dec'], description: 'Decode teks (base64, morse, hex, dll)' },
	{ name: 'morse', aliases: [], description: 'Morse code encode/decode auto-detect' },
	{ name: 'binary', aliases: ['bin'], description: 'Binary encode/decode auto-detect' },
	{ name: 'hash', aliases: [], description: 'Hash teks (sha256, md5, dll)' },
	{ name: 'textpro', aliases: ['tp'], description: 'Text effect maker (100+ efek)' },
	{ name: 'ephoto', aliases: ['ep'], description: 'ePhoto360 effect maker (220+ efek)' },
	{ name: 'photooxy', aliases: ['poxy'], description: 'Photooxy effect maker (115+ efek)' },
	{ name: 'hidetag', aliases: ['ht'], description: 'Tag semua member tanpa mention (admin)' },
	{ name: 'poll', aliases: [], description: 'Buat polling di grup (admin)' },
	{ name: 'setprefix', aliases: [], description: 'Ubah prefix bot (owner)' },
	{ name: 'block', aliases: [], description: 'Block nomor WA (owner)' },
	{ name: 'unblock', aliases: [], description: 'Unblock nomor WA (owner)' },
	// ── Advanced Games ──
	{ name: 'wordle', aliases: ['wd'], description: 'Tebak kata 5 huruf (Wordle)' },
	{ name: 'sudoku', aliases: [], description: 'Sudoku puzzle' },
	{ name: 'typing', aliases: [], description: 'Typing speed test' },
	{ name: 'minesweeper', aliases: ['mine'], description: 'Minesweeper game' },
	{ name: 'math', aliases: [], description: 'Math challenge (streak XP)' },
	{ name: 'guessnum', aliases: ['gn'], description: 'Tebak angka 1-100' },
	{ name: 'wordchain', aliases: ['chain'], description: 'Sambung kata game' },
	{ name: 'memory', aliases: [], description: 'Memory card game' },
	{ name: 'rpstournament', aliases: ['rpst'], description: 'RPS best of 5 tournament' },
	{ name: 'colorguess', aliases: ['cg'], description: 'Tebak warna RGB' },
	{ name: 'flagquiz', aliases: ['flag'], description: 'Tebak bendera negara' },
	// ── Tools & Converters ──
	{ name: 'tts', aliases: [], description: 'Text-to-speech (20+ bahasa)' },
	{ name: 'color', aliases: [], description: 'Color converter (hex/rgb/hsl)' },
	{ name: 'timezone', aliases: ['tz'], description: 'Info timezone dunia' },
	{ name: 'convert', aliases: ['unit'], description: 'Unit converter (50+ konversi)' },
	{ name: 'texttools', aliases: ['tt'], description: 'Text tools (reverse, slug, camel, dll)' },
	{ name: 'password', aliases: ['pw'], description: 'Generate password random' },
	{ name: 'uuid', aliases: [], description: 'Generate UUID v4' },
	{ name: 'barcode', aliases: [], description: 'Generate barcode' },
	{ name: 'placeholder', aliases: [], description: 'Generate placeholder image' },
	{ name: 'lorem', aliases: [], description: 'Lorem ipsum generator' },
	{ name: 'charcount', aliases: [], description: 'Hitung karakter/kata/baris' },
	{ name: 'fileinfo', aliases: [], description: 'Info file media (reply media)' },
	{ name: 'text2img', aliases: ['t2i'], description: 'Teks jadi gambar' },
	{ name: 'rand', aliases: [], description: 'Random number generator' },
	{ name: 'pickrandom', aliases: [], description: 'Pilih random dari opsi' },
	{ name: 'yesno', aliases: [], description: 'Ya atau Tidak random' },
	{ name: 'rate', aliases: [], description: 'Rate sesuatu 0-10' },
	{ name: 'ship', aliases: [], description: 'Ship rate 2 nama' },
	{ name: 'howgay', aliases: [], description: 'How gay meter' },
	{ name: 'howsimp', aliases: [], description: 'How simp meter' },
	{ name: 'howsmart', aliases: [], description: 'How smart meter' },
	{ name: 'waifurate', aliases: [], description: 'Waifu rate 0-100' },
	{ name: 'oneliner', aliases: [], description: 'Joke one liner' },
	{ name: 'quoterandom', aliases: [], description: 'Quote random (quotable)' },
	{ name: 'chuck', aliases: [], description: 'Chuck Norris joke' },
	{ name: 'advice', aliases: [], description: 'Advice random' },
	{ name: 'insult', aliases: [], description: 'Insult random' },
	{ name: 'compliment', aliases: [], description: 'Compliment random' },
	// ── Scraper Commands ──
	{ name: 'twitter', aliases: ['x'], description: 'Twitter/X downloader' },
	{ name: 'facebook', aliases: ['fb'], description: 'Facebook downloader' },
	{ name: 'capcut', aliases: [], description: 'CapCut template info' },
	{ name: 'soundcloud', aliases: ['sc'], description: 'SoundCloud downloader' },
	{ name: 'giphy', aliases: ['gif'], description: 'Search GIF (Giphy)' },
	{ name: 'unsplash', aliases: [], description: 'Search foto (Unsplash)' },
	{ name: 'ghuser', aliases: [], description: 'Info GitHub user' },
	{ name: 'ghrepo', aliases: [], description: 'Info GitHub repo' },
	{ name: 'npm', aliases: [], description: 'Info NPM package' },
	{ name: 'wikien', aliases: [], description: 'Wikipedia English' },
	{ name: 'urban', aliases: [], description: 'Urban Dictionary search' },
	{ name: 'dict', aliases: [], description: 'English dictionary' },
	{ name: 'cryptoinfo', aliases: [], description: 'Info crypto (CoinGecko)' },
	{ name: 'countryinfo', aliases: [], description: 'Info negara (REST Countries)' },
	{ name: 'booksearch', aliases: ['book'], description: 'Cari buku (Open Library)' },
	{ name: 'tvshow', aliases: [], description: 'Cari TV show (TVMaze)' },
	{ name: 'pokemon', aliases: ['poke'], description: 'Info Pokemon (PokéAPI)' },
	{ name: 'swapi', aliases: [], description: 'Star Wars API' },
	{ name: 'deezer', aliases: [], description: 'Cari lagu (Deezer)' },
	{ name: 'itunes', aliases: [], description: 'Cari lagu (iTunes)' },
	{ name: 'hackernews', aliases: ['hn'], description: 'Hacker News top stories' },
	{ name: 'rickmorty', aliases: ['rm'], description: 'Rick & Morty API' },
	{ name: 'animesearch', aliases: [], description: 'Cari anime (MyAnimeList)' },
	{ name: 'mangasearch', aliases: [], description: 'Cari manga (MyAnimeList)' },
	{ name: 'topanime', aliases: [], description: 'Top anime (Jikan)' },
	{ name: 'topmanga', aliases: [], description: 'Top manga (Jikan)' },
	{ name: 'seasonnow', aliases: ['season'], description: 'Anime season sekarang' },
	{ name: 'animequote', aliases: ['aq'], description: 'Quote anime random' },
	{ name: 'waifu', aliases: [], description: 'Waifu/neko/anime image (30+ kategori)' },
	{ name: 'neko', aliases: [], description: 'Neko image' },
	{ name: 'shinobu', aliases: [], description: 'Shinobu image' },
	{ name: 'megumin', aliases: [], description: 'Megumin image' },
	{ name: 'awoo', aliases: [], description: 'Awoo image' },
	{ name: 'cuddle', aliases: [], description: 'Cuddle anime GIF' },
	{ name: 'hug', aliases: [], description: 'Hug anime GIF' },
	{ name: 'kiss', aliases: [], description: 'Kiss anime GIF' },
	{ name: 'pat', aliases: [], description: 'Pat anime GIF' },
	{ name: 'catimg', aliases: [], description: 'Random gambar kucing' },
	{ name: 'dogimg', aliases: [], description: 'Random gambar anjing' },
	{ name: 'foximg', aliases: [], description: 'Random gambar rubah' },
	{ name: 'duckimg', aliases: [], description: 'Random gambar bebek' },
	{ name: 'birdimg', aliases: [], description: 'Random gambar burung' },
	{ name: 'catfact', aliases: [], description: 'Fakta kucing random' },
	{ name: 'dogfact', aliases: [], description: 'Fakta anjing random' },
	{ name: 'numtrivia', aliases: [], description: 'Number trivia' },
	{ name: 'xkcd', aliases: [], description: 'xkcd comic random' },
	{ name: 'earthquake', aliases: ['gempa'], description: 'Info gempa 24 jam terakhir' },
	{ name: 'iss', aliases: [], description: 'Posisi ISS sekarang' },
	{ name: 'spacepeople', aliases: [], description: 'Orang di luar angkasa' },
	{ name: 'spacex', aliases: [], description: 'SpaceX launch terbaru' },
	{ name: 'recipe', aliases: [], description: 'Cari resep makanan' },
	{ name: 'randommeal', aliases: [], description: 'Resep makanan random' },
	{ name: 'cocktail', aliases: [], description: 'Cari resep cocktail' },
	{ name: 'exrate', aliases: [], description: 'Exchange rate (mata uang)' },
	{ name: 'covid', aliases: [], description: 'Statistik COVID global' },
	{ name: 'holiday', aliases: [], description: 'Hari libur Indonesia berikutnya' },
	{ name: 'brewery', aliases: [], description: 'Cari brewery' },
	{ name: 'agify', aliases: [], description: 'Prediksi umur dari nama' },
	{ name: 'genderize', aliases: [], description: 'Prediksi gender dari nama' },
	{ name: 'nationalize', aliases: [], description: 'Prediksi kebangsaan dari nama' },
	{ name: 'randomuser', aliases: [], description: 'Random user profile' },
	{ name: 'iplookup', aliases: [], description: 'Info IP address' },
	// ── Islamic Commands ──
	{ name: 'quran', aliases: ['alquran'], description: 'Ayat Al-Quran (random/surah:ayat/topic)' },
	{ name: 'surah', aliases: [], description: 'Info surah Al-Quran' },
	{ name: 'hadith', aliases: ['hadis'], description: 'Hadits dari koleksi sunnah' },
	{ name: 'asmaulhusna', aliases: ['ah'], description: 'Asmaul Husna (99 Nama Allah)' },
	{ name: 'asmaulhusnalist', aliases: ['ahlist'], description: 'Daftar lengkap 99 Asmaul Husna' },
	{ name: 'dhikr', aliases: ['dzikir'], description: 'Dhikr random + keutamaan' },
	{ name: 'dhikrlist', aliases: [], description: 'Daftar dhikr collection' },
	{ name: 'doa', aliases: ['doaharian'], description: 'Doa harian random/spesifik' },
	{ name: 'doalist', aliases: [], description: 'Daftar doa harian' },
	{ name: 'jadwalshalat', aliases: ['jadwalsholat'], description: 'Jadwal shalat per kota' },
	{ name: 'hijri', aliases: ['hijriyah'], description: 'Konversi ke kalender Hijriyah' },
	{ name: 'islamicevent', aliases: ['islabevent'], description: 'Peristiwa Islam penting' },
	{ name: 'quransearch', aliases: ['qs'], description: 'Cari ayat Al-Quran' },
	{ name: 'tafsir', aliases: [], description: 'Tafsir ayat Al-Quran' },
	{ name: 'juz', aliases: [], description: 'Info juz Al-Quran' },
	{ name: 'islamquote', aliases: [], description: 'Quote Islamic random' },
	{ name: 'qibla', aliases: [], description: 'Arah Qibla dari koordinat' },
	{ name: 'zakat', aliases: [], description: 'Kalkulator zakat' },
	{ name: 'islamicdate', aliases: [], description: 'Tanggal Islam hari ini' },
	{ name: 'asmaulhusnaquiz', aliases: ['ahquiz'], description: 'Quiz Asmaul Husna' },
	{ name: 'quranquiz', aliases: [], description: 'Quiz surah Al-Quran' },
	{ name: 'shalatguide', aliases: [], description: 'Tata cara shalat' },
	{ name: 'wudhuguide', aliases: [], description: 'Tata cara wudhu' },
	{ name: 'assalamualaikum', aliases: ['salam'], description: 'Salam Islamic greeting' },
	{ name: 'islamicfact', aliases: [], description: 'Fakta Islam random' },
	{ name: 'islamicname', aliases: [], description: 'Nama Islami random' },
	{ name: 'dua', aliases: [], description: 'Doa untuk berbagai keperluan' },
	{ name: 'ramadhan', aliases: [], description: 'Info Ramadhan' },
	{ name: 'hajjguide', aliases: [], description: 'Panduan Haji' },
	{ name: 'umrahguide', aliases: [], description: 'Panduan Umrah' },
	{ name: 'fatwa', aliases: [], description: 'Ruling Islam populer' },
	// ── Image Manipulation ──
	{ name: 'imgfx', aliases: [], description: 'Image effects (30+ filter)' },
	{ name: 'overlay', aliases: [], description: 'Image overlays (12+ effect)' },
	{ name: 'triggered', aliases: [], description: 'Triggered effect (reply gambar)' },
	{ name: 'wasted', aliases: [], description: 'Wasted effect (reply gambar)' },
	{ name: 'jail', aliases: [], description: 'Jail effect (reply gambar)' },
	{ name: 'pixelate', aliases: [], description: 'Pixelate effect (reply gambar)' },
	{ name: 'blur', aliases: [], description: 'Blur effect (reply gambar)' },
	{ name: 'invert', aliases: [], description: 'Invert colors (reply gambar)' },
	{ name: 'greyscale', aliases: ['gray'], description: 'Greyscale effect (reply gambar)' },
	{ name: 'sepia', aliases: [], description: 'Sepia effect (reply gambar)' },
	{ name: 'circle', aliases: ['tocircle'], description: 'Circle crop (reply gambar)' },
	{ name: 'deepfry', aliases: [], description: 'Deep fry effect (reply gambar)' },
	{ name: 'wanted', aliases: [], description: 'Wanted poster (reply gambar)' },
	{ name: 'trash', aliases: [], description: 'Trash effect (reply gambar)' },
	{ name: 'petpat', aliases: ['pet'], description: 'Petpat effect (reply gambar)' },
	{ name: 'simpcard', aliases: [], description: 'Simp card (reply gambar)' },
	{ name: 'clown', aliases: [], description: 'Clown effect (reply gambar)' },
	{ name: 'horny', aliases: [], description: 'Horny effect (reply gambar)' },
	{ name: 'hearts', aliases: [], description: 'Hearts overlay (reply gambar)' },
	{ name: 'kissimg', aliases: [], description: 'Kiss overlay (reply gambar)' },
	{ name: 'slap', aliases: [], description: 'Slap overlay (reply gambar)' },
	{ name: 'spank', aliases: [], description: 'Spank overlay (reply gambar)' },
	{ name: 'amiajoke', aliases: [], description: 'Am I A Joke effect (reply gambar)' },
	{ name: 'blurple', aliases: [], description: 'Blurple effect (reply gambar)' },
	{ name: 'golden', aliases: [], description: 'Golden effect (reply gambar)' },
	{ name: 'comrade', aliases: [], description: 'Comrade effect (reply gambar)' },
	{ name: 'glasses', aliases: [], description: 'Glasses effect (reply gambar)' },
	{ name: 'memelist', aliases: [], description: 'Daftar meme templates' },
	{ name: 'effectlist', aliases: [], description: 'Daftar image effects & overlays' },
	{ name: 'caption', aliases: [], description: 'Add caption ke gambar' },
	{ name: 'emojisticker', aliases: [], description: 'Emoji jadi sticker' },
	{ name: 'emojimix', aliases: ['emix'], description: 'Mix 2 emoji jadi sticker' },
	{ name: 'tosticker', aliases: [], description: 'Gambar jadi sticker' },
	{ name: 'toimg', aliases: [], description: 'Sticker jadi gambar' },
	{ name: 'resize', aliases: [], description: 'Resize gambar' },
	{ name: 'rotate', aliases: [], description: 'Rotate gambar' },
	{ name: 'flipimg', aliases: [], description: 'Flip gambar' },
	{ name: 'mirror', aliases: [], description: 'Mirror gambar' },
	// ── More Games ──
	{ name: 'riddle', aliases: [], description: 'Tebak-tebakan riddle' },
	{ name: 'wouldyou', aliases: ['wyr'], description: 'Would You Rather game' },
	{ name: 'neverhave', aliases: ['nhie'], description: 'Never Have I Ever game' },
	{ name: 'thisorthat', aliases: ['tot'], description: 'This or That game' },
	{ name: 'whowould', aliases: ['wwm'], description: 'Who Would Most Likely game' },
	{ name: 'scenario', aliases: [], description: 'What Would You Do scenario' },
	{ name: 'debate', aliases: [], description: 'Random debate topic' },
	{ name: 'hotake', aliases: [], description: 'Hot Take game' },
	{ name: '20questions', aliases: ['20q'], description: '20 Questions game' },
	{ name: 'anagram', aliases: [], description: 'Anagram unscramble game' },
	{ name: 'wordassoc', aliases: ['wa'], description: 'Word Association game' },
	{ name: 'guesssong', aliases: [], description: 'Tebak lagu dari lirik' },
	{ name: 'guessmovie', aliases: [], description: 'Tebak film dari quote' },
	{ name: 'capquiz', aliases: [], description: 'Quiz ibu kota negara' },
	{ name: 'mathquiz', aliases: [], description: 'Quiz matematika' },
	{ name: 'wordguess', aliases: [], description: 'Tebak kata (word guess)' },
	// ── Fun & Utility ──
	{ name: 'roulette', aliases: ['rr'], description: 'Russian roulette game' },
	{ name: 'loveship', aliases: ['love'], description: 'Love compatibility calculator' },
	{ name: 'soulmate', aliases: [], description: 'Soulmate compatibility test' },
	{ name: 'friendship', aliases: [], description: 'Friendship percentage' },
	{ name: 'pickup', aliases: ['pickupline'], description: 'Random pickup line' },
	{ name: 'roast', aliases: [], description: 'Random roast (mild)' },
	{ name: 'uselessfact', aliases: ['uf'], description: 'Random useless fact' },
	{ name: 'dadjoke', aliases: [], description: 'Dad joke random' },
	{ name: 'chucknorris', aliases: ['cn'], description: 'Chuck Norris joke' },
	{ name: 'motivation', aliases: [], description: 'Motivational quote' },
	{ name: 'affirmation', aliases: [], description: 'Positive affirmation' },
	{ name: 'yomama', aliases: [], description: 'Yo mama joke' },
	{ name: 'pun', aliases: [], description: 'Random pun' },
	{ name: 'fortune', aliases: [], description: 'Fortune cookie message' },
	{ name: 'horoscope', aliases: [], description: 'Horoscope from API' },
	{ name: 'zodiac', aliases: [], description: 'Zodiac sign from birth date' },
	{ name: 'lucky', aliases: [], description: 'Lucky number generator' },
	{ name: 'mood', aliases: [], description: 'Random mood/emoji' },
	{ name: 'vibe', aliases: [], description: 'Vibe check' },
	{ name: 'personality', aliases: [], description: 'Random personality type' },
	{ name: 'spiritanimal', aliases: [], description: 'Random spirit animal' },
	{ name: 'superpower', aliases: [], description: 'Random superpower' },
	{ name: 'patronus', aliases: [], description: 'Harry Potter patronus' },
	// ── Font/Text Styles ──
	{ name: 'bold', aliases: [], description: '𝗕𝗼𝗹𝗱 text style' },
	{ name: 'italic', aliases: [], description: '𝘐𝘵𝘢𝘭𝘪𝘤 text style' },
	{ name: 'bolditalic', aliases: ['bi'], description: '𝘽𝙤𝙡𝙙 𝙄𝙩𝙖𝙡𝙞𝙘 style' },
	{ name: 'monospace', aliases: ['mono'], description: '𝙼𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎 style' },
	{ name: 'script', aliases: [], description: '𝒮𝒸𝓇𝒾𝓅𝓉 style' },
	{ name: 'boldscript', aliases: ['bscript'], description: '𝓑𝓸𝓵𝓭 𝓢𝓬𝓻𝓲𝓹𝓽 style' },
	{ name: 'fraktur', aliases: [], description: '𝔉𝔯𝔞𝔨𝔱𝔲𝔯 style' },
	{ name: 'doublestruck', aliases: ['ds'], description: '𝔻𝕠𝕦𝕓𝕝𝕖 style' },
	{ name: 'circled', aliases: [], description: 'Ⓒⓘⓡⓒⓛⓔⓓ style' },
	{ name: 'squared', aliases: [], description: '🅂🅀🅄🄰🅁🄴🄳 style' },
	{ name: 'smallcaps', aliases: ['sc'], description: 'ꜱᴍᴀʟʟ ᴄᴀᴘꜱ style' },
	{ name: 'upsidedown', aliases: ['ud'], description: 'uʍop ǝpısdn style' },
	{ name: 'fullwidth', aliases: ['fw'], description: 'Ｆｕｌｌｗｉｄｔｈ style' },
	{ name: 'strikethrough', aliases: ['strike'], description: 'S̶t̶r̶i̶k̶e̶ style' },
	{ name: 'underline', aliases: ['ul'], description: 'U̲n̲d̲e̲r̲ style' },
	{ name: 'crossed', aliases: [], description: 'C̸r̸o̸s̸s̸e̸d̸ style' },
	{ name: 'zalgo', aliases: [], description: 'Z̴a̷l̶g̸o̴ style' },
	{ name: 'bubble', aliases: [], description: 'ⓑⓤⓑⓑⓛⓔ style' },
	{ name: 'regional', aliases: [], description: '🇦 🇧 🇨 style' },
	{ name: 'braille', aliases: [], description: '⠃⠗⠁⠊⠇⠇⠑ style' },
	{ name: 'nato', aliases: [], description: 'NATO phonetic alphabet' },
	{ name: 'hex', aliases: [], description: 'Hexadecimal encode' },
	{ name: 'leet', aliases: ['l33t'], description: 'L337 5p34k style' },
	{ name: 'reverse', aliases: [], description: 'esreveR text' },
	{ name: 'title', aliases: [], description: 'Title Case text' },
	{ name: 'alternating', aliases: ['alt'], description: 'aLtErNaTiNg case' },
	{ name: 'wide', aliases: [], description: 'Ｗ ｉ ｄ ｅ spaced' },
	// ── Scraper v2 ──
	{ name: 'recipe2', aliases: [], description: 'Cari resep makanan (TheMealDB)' },
	{ name: 'randomrecipe', aliases: [], description: 'Resep makanan random' },
	{ name: 'cocktail2', aliases: [], description: 'Cari resep cocktail (TheCocktailDB)' },
	{ name: 'randomcocktail', aliases: [], description: 'Resep cocktail random' },
	{ name: 'beer', aliases: [], description: 'Random beer info' },
	{ name: 'foodimg', aliases: [], description: 'Random food image' },
	{ name: 'coffeeimg', aliases: [], description: 'Random coffee image' },
	{ name: 'nutrition', aliases: [], description: 'Info nutrisi makanan' },
	{ name: 'openlibrary', aliases: ['ol'], description: 'Cari buku Open Library' },
	{ name: 'randombook', aliases: [], description: 'Buku random Open Library' },
	{ name: 'gutenberg', aliases: [], description: 'Cari ebook gratis' },
	{ name: 'poetry', aliases: [], description: 'Random poem' },
	{ name: 'quote2', aliases: [], description: 'Quote random (Quotable)' },
	{ name: 'advice2', aliases: [], description: 'Advice random (AdviceSlip)' },
	{ name: 'affirmation2', aliases: [], description: 'Positive affirmation' },
	{ name: 'bored', aliases: [], description: 'Random activity suggestion' },
	{ name: 'trivia2', aliases: [], description: 'Trivia question (Open Trivia DB)' },
	{ name: 'xkcdrandom', aliases: [], description: 'xkcd comic random' },
	{ name: 'joke2', aliases: [], description: 'Joke random (JokeAPI)' },
	{ name: 'dadjoke2', aliases: [], description: 'Dad joke (icanhazdadjoke)' },
	{ name: 'chuck2', aliases: [], description: 'Chuck Norris joke v2' },
	{ name: 'uselessfact2', aliases: [], description: 'Useless fact v2' },
	{ name: 'numberfact', aliases: [], description: 'Number trivia' },
	{ name: 'datefact', aliases: [], description: 'Date fact' },
	{ name: 'yearfact', aliases: [], description: 'Year fact' },
	{ name: 'onthisday', aliases: [], description: 'Historical events today' },
	{ name: 'sunrise', aliases: [], description: 'Sunrise/sunset times' },
	{ name: 'airquality', aliases: ['aqi'], description: 'Air quality index' },
	{ name: 'periodic', aliases: ['element'], description: 'Info elemen kimia' },
	{ name: 'planet', aliases: [], description: 'Info planet tata surya' },
	{ name: 'satellite', aliases: [], description: 'Posisi ISS' },
	{ name: 'aurora', aliases: [], description: 'Aurora forecast' },
	{ name: 'speedrun', aliases: [], description: 'Speedrun game data' },
	{ name: 'steam', aliases: [], description: 'Steam game search' },
	{ name: 'gamedeal', aliases: [], description: 'Game deals (CheapShark)' },
	// ── Islamic v2 (lib/islamic.js) ──
	{ name: 'ayatkursi', aliases: [], description: 'Ayat Kursi lengkap + terjemahan' },
	{ name: 'juzamma', aliases: [], description: 'Juz Amma (37 surah pendek)' },
	{ name: 'kisahnabi', aliases: [], description: 'Kisah 25 Nabi & Rasul' },
	{ name: 'niatsholat', aliases: [], description: 'Niat 5 waktu shalat' },
	{ name: 'tahlil', aliases: [], description: 'Bacaan tahlil lengkap' },
	{ name: 'wirid', aliases: [], description: 'Wirid setelah shalat' },
	{ name: 'dzikir', aliases: [], description: 'Dzikir pagi/petang' },
	{ name: 'doaqlb', aliases: [], description: 'Doa Qunut/Iftitah/Sujud/Ruku/Tasyahud' },
	{ name: 'kisahsahabat', aliases: [], description: 'Kisah 10 Sahabat Nabi' },
	{ name: 'dalil', aliases: [], description: 'Dalil Al-Quran per topik' },
	{ name: 'hukumislam', aliases: [], description: '12 Hukum Islam populer' },
	{ name: 'sejarahislam', aliases: [], description: '20 Peristiwa sejarah Islam' },
	{ name: 'shalawat', aliases: [], description: '10 Kumpulan shalawat' },
	{ name: 'doamakan', aliases: [], description: 'Doa sebelum/sesudah makan' },
	{ name: 'doatidur', aliases: [], description: 'Doa sebelum tidur' },
	{ name: 'doamasjid', aliases: [], description: 'Doa masuk/keluar masjid' },
	{ name: 'doawudhu', aliases: [], description: 'Doa wudhu' },
	{ name: 'doaparents', aliases: [], description: 'Doa untuk orang tua' },
	{ name: 'doasick', aliases: [], description: 'Doa untuk orang sakit' },
	{ name: 'doatravel', aliases: [], description: 'Doa bepergian' },
	{ name: 'doastudy', aliases: [], description: 'Doa belajar' },
	{ name: 'doamarriage', aliases: [], description: 'Doa pernikahan' },
	{ name: 'doadeath', aliases: [], description: 'Doa untuk orang meninggal' },
	{ name: 'doarizqi', aliases: [], description: 'Doa rezeki' },
	{ name: 'doaforgiveness', aliases: [], description: 'Doa istighfar' },
	{ name: 'doaprophet', aliases: [], description: 'Shalawat Ibrahimiyah' },
	{ name: 'doaprotection', aliases: [], description: 'Doa perlindungan' },
	{ name: 'tasbih', aliases: [], description: 'Tasbih counter' },
	{ name: 'hijriah', aliases: [], description: 'Konversi Masehi ke Hijriah' },
	{ name: 'imsak', aliases: [], description: 'Jadwal imsakiyah per kota' },
	{ name: 'kajian', aliases: [], description: '11 Topik kajian Islam' },
	{ name: 'mufti', aliases: [], description: '10 Fatwa populer' },
	{ name: 'maulid', aliases: [], description: 'Bacaan Maulid Nabi' },
	{ name: 'isra', aliases: [], description: 'Kisah Isra Miraj' },
	{ name: 'nabiakhir', aliases: [], description: '12 Tanda kiamat' },
	{ name: 'syahadat', aliases: [], description: 'Syahadat text' },
	{ name: 'jumat', aliases: [], description: 'Sunnah Jumat' },
	{ name: 'tahajjud', aliases: [], description: 'Panduan shalat Tahajjud' },
	{ name: 'iduladha', aliases: [], description: 'Info Idul Adha' },
	{ name: 'dhuha', aliases: [], description: 'Panduan shalat Dhuha' }
]

export const listCommands = () => commandList
