const commandList = [
	{ name: 'menu', aliases: ['help', 'start'], description: 'Tampilkan menu bot' },
	{ name: 'ping', aliases: ['p'], description: 'Cek respon bot' },
	{ name: 'eval', aliases: ['ev'], description: 'Evaluasi kode JavaScript owner' },
	{ name: 'backup', aliases: ['dbbackup'], description: 'Backup database owner' },
	{ name: 'restore', aliases: ['dbrestore'], description: 'Restore database dari backup JSON owner' },
	{ name: 'logs', aliases: ['logtail'], description: 'Tail log runtime owner' },
	{ name: 'remind', aliases: ['reminder', 'schedule', 'scheduler'], description: 'Set reminder owner' },
	{ name: 'sticker', aliases: ['s'], description: 'Ubah image/video jadi sticker' },
	{ name: 'toaudio', aliases: ['tomp3'], description: 'Ubah video/audio jadi MP3' },
	{ name: 'toptt', aliases: ['vn'], description: 'Ubah video/audio jadi voice note' },
	{ name: 'tovid', aliases: ['togif'], description: 'Ubah sticker jadi video/GIF' },
	{ name: 'update', aliases: ['upgrade'], description: 'Update file bot dan install dependency' },
	{ name: 'tourl', aliases: ['urlfile'], description: 'Upload media ke Catbox' },
	{ name: 'short', aliases: ['shortlink'], description: 'Buat shortlink TinyURL' },
	{ name: 'qr', aliases: ['qrcode'], description: 'Generate QR code dari text/URL' },
	{ name: 'readqr', aliases: ['qrread', 'scanqr'], description: 'Baca QR dari gambar atau URL gambar' },
	{ name: 'tiktok', aliases: ['tt'], description: 'TikTok native: URL → no-watermark, query → search, @user → profil' },
	{ name: 'ttuser', aliases: ['ttprofile', 'tikuser'], description: 'Cek profil TikTok by @username' },
	{ name: 'instagram', aliases: ['ig'], description: 'Downloader Instagram atau tombol halaman asli' },
	{ name: 'youtube', aliases: ['yt', 'ytmp4'], description: 'Downloader YouTube atau tombol halaman asli' },
	{ name: 'lyrics', aliases: ['lirik', 'ly'], description: 'Cari lyric lagu (Genius + lyrics.ovh)' },
	{ name: 'translate', aliases: ['tr', 'tl'], description: 'Translate teks (default ke Bahasa Indonesia)' },
	{ name: 'detect', aliases: ['detlang', 'dlang'], description: 'Deteksi bahasa dari teks' },
	{ name: 'image', aliases: ['imagine', 'ai', 'gen'], description: 'Generate gambar AI dari prompt (Pollinations)' },
	{ name: 'imagemodels', aliases: ['models', 'aimodels'], description: 'List model AI image yang tersedia' },
	{ name: 'wiki', aliases: ['wikipedia'], description: 'Cari artikel Wikipedia (id)' },
	{ name: 'surah', aliases: ['quran'], description: 'Tampilkan surah Al-Quran by nomor' },
	{ name: 'ayat', aliases: [], description: 'Tampilkan satu ayat (.ayat 2 255)' },
	{ name: 'surahlist', aliases: ['daftarsurah'], description: 'Daftar 114 surah Al-Quran' },
	{ name: 'sholat', aliases: ['jadwalsholat'], description: 'Jadwal sholat hari ini per kota' },
	{ name: 'cuaca', aliases: ['weather'], description: 'Cuaca global via wttr.in' },
	{ name: 'bmkg', aliases: [], description: 'Cuaca resmi BMKG (Indonesia)' },
	{ name: 'quote', aliases: ['kata'], description: 'Quote random' },
	{ name: 'animequote', aliases: ['anime-quote'], description: 'Quote anime random' },
	{ name: 'fact', aliases: ['fakta'], description: 'Random useless fact' },
	{ name: 'joke', aliases: ['lelucon'], description: 'Random joke (jokeapi)' },
	{ name: 'meme', aliases: [], description: 'Random meme dari Reddit' },
	{ name: 'kateglo', aliases: ['kbbi'], description: 'Kamus Indonesia (definisi + sinonim)' },
	{ name: 'pypi', aliases: ['pip'], description: 'Info package PyPI' },
	{ name: 'ghtrend', aliases: ['github-trending', 'gh-trend'], description: 'GitHub trending repos' },
	{ name: 'ytsearch', aliases: ['youtube-search'], description: 'Cari video YouTube' },
	{ name: 'wp', aliases: ['wallpaper', 'wallhaven'], description: 'Cari wallpaper di Wallhaven' },
	{ name: 'kurs', aliases: ['currency'], description: 'Konversi mata uang (.kurs USD IDR 50)' },
	{ name: 'rates', aliases: ['rate'], description: 'Daftar kurs populer dari base currency' },
	{ name: 'ip', aliases: ['iplookup'], description: 'Lookup info IP / lokasi' },
	{ name: 'reddit', aliases: ['r'], description: 'Lihat post subreddit (.reddit memes top)' },
	{ name: 'berita', aliases: ['news'], description: 'Headline berita Indonesia (CNN/Antara/dll)' },
	{ name: 'ss', aliases: ['screenshot'], description: 'Screenshot halaman web' },
	{ name: 'mediafire', aliases: ['mf'], description: 'Direct link Mediafire dari URL' },
	{ name: 'pin', aliases: ['pinterest', 'pins'], description: 'Scrape media Pinterest' },
	{ name: 'pinnext', aliases: ['nextpin'], description: 'Foto Pinterest berikutnya' },
	{ name: 'anime', aliases: ['ani'], description: 'Cari anime di Samehadaku' },
	{ name: 'stream', aliases: ['samehadaku', 'nonton'], description: 'Ambil stream episode Samehadaku' },
	{ name: 'streamselect', aliases: ['pilihstream'], description: 'Pilih episode stream Samehadaku' },
	{ name: 'streamnext', aliases: ['nextstream'], description: 'Server stream Samehadaku berikutnya' },
	{ name: 'otakudesu', aliases: ['otaku'], description: 'Cari anime di Otakudesu' },
	{ name: 'otakudesulatest', aliases: ['otakulatest', 'otakulatest'], description: 'Episode terbaru Otakudesu' },
	{ name: 'otakudesustream', aliases: ['otakustream'], description: 'Ambil stream episode Otakudesu' },
	{ name: 'otakudesunext', aliases: ['otakunext'], description: 'Hasil/server Otakudesu berikutnya' },
	{ name: 'otakudesuselect', aliases: ['otakuselect'], description: 'Pilih episode stream Otakudesu' },
	{ name: 'anoboy', aliases: ['ano'], description: 'Cari anime di Anoboy' },
	{ name: 'anoboylatest', aliases: ['anolatest', 'anolatest'], description: 'Episode terbaru Anoboy' },
	{ name: 'anoboystream', aliases: ['anostream'], description: 'Ambil stream episode Anoboy' },
	{ name: 'anoboynext', aliases: ['anonext'], description: 'Hasil/server Anoboy berikutnya' },
	{ name: 'anoboyselect', aliases: ['anoselect'], description: 'Pilih episode stream Anoboy' },
	{ name: 'spotify', aliases: ['sp'], description: 'Cari lagu di Spotify' },
	{ name: 'spotifydl', aliases: ['spdl'], description: 'Download lagu dari Spotify URL' },
	{ name: 'spotifynext', aliases: ['spnext'], description: 'Hasil Spotify berikutnya' },
	{ name: 'topanime', aliases: ['topani'], description: 'Top anime Samehadaku' },
	{ name: 'seasonanime', aliases: ['season'], description: 'Anime season sekarang' },
	{ name: 'idch', aliases: ['cekidch', 'cekid'], description: 'Cek ID channel WhatsApp' },
	{ name: 'role', aliases: ['profile', 'me'], description: 'Cek role user' },
	{ name: 'setnama', aliases: ['setname', 'nama'], description: 'Set nama profile bot' },
	{ name: 'welcome', aliases: ['setwelcome'], description: 'Aktif/nonaktif welcome grup' },
	{ name: 'leave', aliases: ['setleave'], description: 'Aktif/nonaktif leave grup' },
	{ name: 'antilink', aliases: ['anti-link'], description: 'Aktif/nonaktif anti-link grup' },
	{ name: 'antispam', aliases: ['anti-spam'], description: 'Aktif/nonaktif anti-spam grup' },
	{ name: 'antidelete', aliases: ['anti-delete'], description: 'Aktif/nonaktif anti-delete grup' },
	{ name: 'groupsetting', aliases: ['groupsettings'], description: 'Cek setting grup' },
	{ name: 'warn', aliases: [], description: 'Beri warn member grup' },
	{ name: 'unwarn', aliases: [], description: 'Kurangi warn member grup' },
	{ name: 'kick', aliases: ['remove'], description: 'Keluarkan member grup' },
	{ name: 'promote', aliases: [], description: 'Jadikan admin grup' },
	{ name: 'demote', aliases: [], description: 'Turunkan admin grup' },
	{ name: 'register', aliases: ['daftar'], description: 'Daftar sebagai member' },
	{ name: 'unregister', aliases: ['unreg'], description: 'Hapus status member' },
	{ name: 'button', aliases: ['buttons'], description: 'Demo quick reply button' },
	{ name: 'list', aliases: ['pilih'], description: 'Demo button pilihan/list' },
	{ name: 'link', aliases: ['url'], description: 'Demo tombol buka link' },
	{ name: 'copy', aliases: ['code'], description: 'Demo tombol salin text' },
	{ name: 'call', aliases: ['phone'], description: 'Demo tombol telepon' },
	{ name: 'owner', aliases: ['creator'], description: 'Tampilkan owner bot' },
	{ name: 'id', aliases: ['jid'], description: 'Cek JID chat' }
]

export const listCommands = () => commandList
