export const config = {
	name: 'Diana Bot',
	version: '1.0.0',
	prefixes: ['!', '.', '/'],
	ownerNumber: '12365021517',
	adminNumbers: [],
	premiumNumbers: [],
	pairingNumber: '',
	pairingCode: 'DIANABOT',
	pairingWaitMs: 180000,
	resetStalePairingSession: true,
	browserName: 'Safari',
	waLogLevel: 'silent',
	sessionDir: './database/session',
	databaseFile: './database/data.json',
	logLevel: 'info',
	autoRead: false,
	customReply: {
		enabled: true,
		forwarded: true,
		forwardingScore: 0,
		channelId: '120363423953253980@newsletter',
		channelName: '👧 ᴅɪᴀɴᴀ - ʙᴏᴛ',
		title: '👧 ᴅɪᴀɴᴀ - ʙᴏᴛ',
		body: 'Powered by shileys',
		largeThumbnail: false,
		thumbnailUrl: 'https://files.catbox.moe/qmspao.jpg',
		sourceUrl: 'https://github.com/Shikytemo/diana-bot'
	}
}
